#
#eureka:
#  server:
#    enabled: false
#  client:
#    registerWithEureka: false
#    fetchRegistry: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://10.44.145.103:8761/eureka/
#      defaultZone: http://101.200.181.234:8761/eureka/

  instance:
    preferIpAddress: true
    home-page-url-path: ${server.contextPath}/
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health

