
# Spring properties
spring:
  application:
    name: comm-comsumer  # Identify this application


ribbon:
  eureka:
    enabled: true

# HTTP Server
server:
  port: 8080   # HTTP (Tomcat) port

## acutor 设置
management:
  security:
    enabled: false
    role: SUPERUSER

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin
