spring:
  application:
    name: user-api

server:
  port: 0
  context-path: /${spring.application.name}

eureka:
  client:
    serviceUrl:
#          defaultZone: http://10.44.145.103:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
#    initialInstanceInfoReplicationIntervalSeconds:
#    lease:
#      duration: 5
  instance:
    registryFetchIntervalSeconds: 1
    leaseRenewalIntervalInSeconds: 2

    metadata-map: #    leaseExpirationDurationInSeconds: 5
      serviceMark: ONLINE