
spring:
  application:
    name: zy-oauth-server
    version: 0.0.1

server:
  contextPath: /zy-oauth-server
  port: 8081

#  profiles:
#    active: test

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://10.44.145.103:8761/eureka/
  instance:
    preferIpAddress: true
    home-page-url-path: ${server.contextPath}/
    statusPageUrlPath: ${server.contextPath}/info
    healthCheckUrlPath: ${server.contextPath}/health


management:
  security:
    enabled: false
security:
  basic:
    enabled: false

#logging:
#  level: debug