
server:
  port: 9966

spring:
  datasource:
    #spanstore-jdbc-0.9.3.jar
    schema: classpath:/mysql.sql
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
      # Switch this on to create the schema on startup:
    initialize: true
    continueOnError: true