package org.louis.hometutor.po;

import com.foo.louis.Hello;

public class UserInfo extends Hello {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_user_info.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_user_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_user_info.isuse
     *
     * @mbggenerated
     */
    private Integer isuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column family_user_info.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_user_info
     *
     * @mbggenerated
     */
    public UserInfo(Long id, String name, Integer isuse, String password) {
        this.id = id;
        this.name = name;
        this.isuse = isuse;
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_user_info.id
     *
     * @return the value of family_user_info.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_user_info.name
     *
     * @return the value of family_user_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_user_info.isuse
     *
     * @return the value of family_user_info.isuse
     *
     * @mbggenerated
     */
    public Integer getIsuse() {
        return isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column family_user_info.password
     *
     * @return the value of family_user_info.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }
}