// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestModel.proto

package com.xiyuan.demo.model;

public final class TestModel {
    private TestModel() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface RequestOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string id = 1;

        /**
         * <code>required string id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>required string id = 1;</code>
         */
        String getId();

        /**
         * <code>required string id = 1;</code>
         */
        com.google.protobuf.ByteString
        getIdBytes();

        // required string deviceId = 2;

        /**
         * <code>required string deviceId = 2;</code>
         */
        boolean hasDeviceId();

        /**
         * <code>required string deviceId = 2;</code>
         */
        String getDeviceId();

        /**
         * <code>required string deviceId = 2;</code>
         */
        com.google.protobuf.ByteString
        getDeviceIdBytes();

        // required string userId = 3;

        /**
         * <code>required string userId = 3;</code>
         */
        boolean hasUserId();

        /**
         * <code>required string userId = 3;</code>
         */
        String getUserId();

        /**
         * <code>required string userId = 3;</code>
         */
        com.google.protobuf.ByteString
        getUserIdBytes();

        // required string method = 4;

        /**
         * <code>required string method = 4;</code>
         */
        boolean hasMethod();

        /**
         * <code>required string method = 4;</code>
         */
        String getMethod();

        /**
         * <code>required string method = 4;</code>
         */
        com.google.protobuf.ByteString
        getMethodBytes();
    }

    /**
     * Protobuf type {@code Request}
     */
    public static final class Request extends
            com.google.protobuf.GeneratedMessage
            implements RequestOrBuilder {
        // Use Request.newBuilder() to construct.
        private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Request(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final Request defaultInstance;

        public static Request getDefaultInstance() {
            return defaultInstance;
        }

        public Request getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Request(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            id_ = input.readBytes();
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            deviceId_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            userId_ = input.readBytes();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            method_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TestModel.internal_static_Request_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TestModel.internal_static_Request_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Request.class, Builder.class);
        }

        public static com.google.protobuf.Parser<Request> PARSER =
                new com.google.protobuf.AbstractParser<Request>() {
                    public Request parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Request(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<Request> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required string id = 1;
        public static final int ID_FIELD_NUMBER = 1;
        private Object id_;

        /**
         * <code>required string id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string id = 1;</code>
         */
        public String getId() {
            Object ref = id_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    id_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getIdBytes() {
            Object ref = id_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string deviceId = 2;
        public static final int DEVICEID_FIELD_NUMBER = 2;
        private Object deviceId_;

        /**
         * <code>required string deviceId = 2;</code>
         */
        public boolean hasDeviceId() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string deviceId = 2;</code>
         */
        public String getDeviceId() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    deviceId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string deviceId = 2;</code>
         */
        public com.google.protobuf.ByteString
        getDeviceIdBytes() {
            Object ref = deviceId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                deviceId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string userId = 3;
        public static final int USERID_FIELD_NUMBER = 3;
        private Object userId_;

        /**
         * <code>required string userId = 3;</code>
         */
        public boolean hasUserId() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string userId = 3;</code>
         */
        public String getUserId() {
            Object ref = userId_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    userId_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string userId = 3;</code>
         */
        public com.google.protobuf.ByteString
        getUserIdBytes() {
            Object ref = userId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                userId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string method = 4;
        public static final int METHOD_FIELD_NUMBER = 4;
        private Object method_;

        /**
         * <code>required string method = 4;</code>
         */
        public boolean hasMethod() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>required string method = 4;</code>
         */
        public String getMethod() {
            Object ref = method_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    method_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string method = 4;</code>
         */
        public com.google.protobuf.ByteString
        getMethodBytes() {
            Object ref = method_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                method_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            id_ = "";
            deviceId_ = "";
            userId_ = "";
            method_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasDeviceId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasUserId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMethod()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getDeviceIdBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getUserIdBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, getMethodBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getDeviceIdBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getUserIdBytes());
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getMethodBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Request parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Request parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Request parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Request parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Request parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Request parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Request parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static Request parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static Request parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Request parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(Request prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Request}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements RequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TestModel.internal_static_Request_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TestModel.internal_static_Request_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Request.class, Builder.class);
            }

            // Construct using com.xiyuan.demo.model.TestModel.Request.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                id_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                deviceId_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                userId_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                method_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestModel.internal_static_Request_descriptor;
            }

            public Request getDefaultInstanceForType() {
                return Request.getDefaultInstance();
            }

            public Request build() {
                Request result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Request buildPartial() {
                Request result = new Request(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.deviceId_ = deviceId_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.userId_ = userId_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.method_ = method_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Request) {
                    return mergeFrom((Request) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Request other) {
                if (other == Request.getDefaultInstance()) return this;
                if (other.hasId()) {
                    bitField0_ |= 0x00000001;
                    id_ = other.id_;
                    onChanged();
                }
                if (other.hasDeviceId()) {
                    bitField0_ |= 0x00000002;
                    deviceId_ = other.deviceId_;
                    onChanged();
                }
                if (other.hasUserId()) {
                    bitField0_ |= 0x00000004;
                    userId_ = other.userId_;
                    onChanged();
                }
                if (other.hasMethod()) {
                    bitField0_ |= 0x00000008;
                    method_ = other.method_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasId()) {

                    return false;
                }
                if (!hasDeviceId()) {

                    return false;
                }
                if (!hasUserId()) {

                    return false;
                }
                if (!hasMethod()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Request parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Request) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required string id = 1;
            private Object id_ = "";

            /**
             * <code>required string id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string id = 1;</code>
             */
            public String getId() {
                Object ref = id_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    id_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getIdBytes() {
                Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string id = 1;</code>
             */
            public Builder setId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }

            /**
             * <code>required string id = 1;</code>
             */
            public Builder setIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            // required string deviceId = 2;
            private Object deviceId_ = "";

            /**
             * <code>required string deviceId = 2;</code>
             */
            public boolean hasDeviceId() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string deviceId = 2;</code>
             */
            public String getDeviceId() {
                Object ref = deviceId_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    deviceId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string deviceId = 2;</code>
             */
            public com.google.protobuf.ByteString
            getDeviceIdBytes() {
                Object ref = deviceId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    deviceId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string deviceId = 2;</code>
             */
            public Builder setDeviceId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                deviceId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string deviceId = 2;</code>
             */
            public Builder clearDeviceId() {
                bitField0_ = (bitField0_ & ~0x00000002);
                deviceId_ = getDefaultInstance().getDeviceId();
                onChanged();
                return this;
            }

            /**
             * <code>required string deviceId = 2;</code>
             */
            public Builder setDeviceIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                deviceId_ = value;
                onChanged();
                return this;
            }

            // required string userId = 3;
            private Object userId_ = "";

            /**
             * <code>required string userId = 3;</code>
             */
            public boolean hasUserId() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string userId = 3;</code>
             */
            public String getUserId() {
                Object ref = userId_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    userId_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string userId = 3;</code>
             */
            public com.google.protobuf.ByteString
            getUserIdBytes() {
                Object ref = userId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    userId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string userId = 3;</code>
             */
            public Builder setUserId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                userId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string userId = 3;</code>
             */
            public Builder clearUserId() {
                bitField0_ = (bitField0_ & ~0x00000004);
                userId_ = getDefaultInstance().getUserId();
                onChanged();
                return this;
            }

            /**
             * <code>required string userId = 3;</code>
             */
            public Builder setUserIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                userId_ = value;
                onChanged();
                return this;
            }

            // required string method = 4;
            private Object method_ = "";

            /**
             * <code>required string method = 4;</code>
             */
            public boolean hasMethod() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>required string method = 4;</code>
             */
            public String getMethod() {
                Object ref = method_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    method_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string method = 4;</code>
             */
            public com.google.protobuf.ByteString
            getMethodBytes() {
                Object ref = method_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    method_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string method = 4;</code>
             */
            public Builder setMethod(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                method_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string method = 4;</code>
             */
            public Builder clearMethod() {
                bitField0_ = (bitField0_ & ~0x00000008);
                method_ = getDefaultInstance().getMethod();
                onChanged();
                return this;
            }

            /**
             * <code>required string method = 4;</code>
             */
            public Builder setMethodBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                method_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Request)
        }

        static {
            defaultInstance = new Request(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:Request)
    }

    public interface ResponceOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required string id = 1;

        /**
         * <code>required string id = 1;</code>
         */
        boolean hasId();

        /**
         * <code>required string id = 1;</code>
         */
        String getId();

        /**
         * <code>required string id = 1;</code>
         */
        com.google.protobuf.ByteString
        getIdBytes();

        // required bool success = 2;

        /**
         * <code>required bool success = 2;</code>
         */
        boolean hasSuccess();

        /**
         * <code>required bool success = 2;</code>
         */
        boolean getSuccess();

        // required string msg = 3;

        /**
         * <code>required string msg = 3;</code>
         */
        boolean hasMsg();

        /**
         * <code>required string msg = 3;</code>
         */
        String getMsg();

        /**
         * <code>required string msg = 3;</code>
         */
        com.google.protobuf.ByteString
        getMsgBytes();
    }

    /**
     * Protobuf type {@code Responce}
     */
    public static final class Responce extends
            com.google.protobuf.GeneratedMessage
            implements ResponceOrBuilder {
        // Use Responce.newBuilder() to construct.
        private Responce(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private Responce(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        private static final Responce defaultInstance;

        public static Responce getDefaultInstance() {
            return defaultInstance;
        }

        public Responce getDefaultInstanceForType() {
            return defaultInstance;
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private Responce(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            id_ = input.readBytes();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            success_ = input.readBool();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            msg_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return TestModel.internal_static_Responce_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return TestModel.internal_static_Responce_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Responce.class, Builder.class);
        }

        public static com.google.protobuf.Parser<Responce> PARSER =
                new com.google.protobuf.AbstractParser<Responce>() {
                    public Responce parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Responce(input, extensionRegistry);
                    }
                };

        @Override
        public com.google.protobuf.Parser<Responce> getParserForType() {
            return PARSER;
        }

        private int bitField0_;
        // required string id = 1;
        public static final int ID_FIELD_NUMBER = 1;
        private Object id_;

        /**
         * <code>required string id = 1;</code>
         */
        public boolean hasId() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required string id = 1;</code>
         */
        public String getId() {
            Object ref = id_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    id_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string id = 1;</code>
         */
        public com.google.protobuf.ByteString
        getIdBytes() {
            Object ref = id_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required bool success = 2;
        public static final int SUCCESS_FIELD_NUMBER = 2;
        private boolean success_;

        /**
         * <code>required bool success = 2;</code>
         */
        public boolean hasSuccess() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required bool success = 2;</code>
         */
        public boolean getSuccess() {
            return success_;
        }

        // required string msg = 3;
        public static final int MSG_FIELD_NUMBER = 3;
        private Object msg_;

        /**
         * <code>required string msg = 3;</code>
         */
        public boolean hasMsg() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>required string msg = 3;</code>
         */
        public String getMsg() {
            Object ref = msg_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    msg_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string msg = 3;</code>
         */
        public com.google.protobuf.ByteString
        getMsgBytes() {
            Object ref = msg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                msg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            id_ = "";
            success_ = false;
            msg_ = "";
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasId()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasSuccess()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasMsg()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBool(2, success_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getMsgBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getIdBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, success_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getMsgBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static Responce parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Responce parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Responce parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Responce parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Responce parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Responce parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Responce parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static Responce parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static Responce parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static Responce parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder(Responce prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Responce}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements ResponceOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return TestModel.internal_static_Responce_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return TestModel.internal_static_Responce_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Responce.class, Builder.class);
            }

            // Construct using com.xiyuan.demo.model.TestModel.Responce.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                id_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                success_ = false;
                bitField0_ = (bitField0_ & ~0x00000002);
                msg_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return TestModel.internal_static_Responce_descriptor;
            }

            public Responce getDefaultInstanceForType() {
                return Responce.getDefaultInstance();
            }

            public Responce build() {
                Responce result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public Responce buildPartial() {
                Responce result = new Responce(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.id_ = id_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.success_ = success_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.msg_ = msg_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Responce) {
                    return mergeFrom((Responce) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Responce other) {
                if (other == Responce.getDefaultInstance()) return this;
                if (other.hasId()) {
                    bitField0_ |= 0x00000001;
                    id_ = other.id_;
                    onChanged();
                }
                if (other.hasSuccess()) {
                    setSuccess(other.getSuccess());
                }
                if (other.hasMsg()) {
                    bitField0_ |= 0x00000004;
                    msg_ = other.msg_;
                    onChanged();
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasId()) {

                    return false;
                }
                if (!hasSuccess()) {

                    return false;
                }
                if (!hasMsg()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                Responce parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (Responce) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            // required string id = 1;
            private Object id_ = "";

            /**
             * <code>required string id = 1;</code>
             */
            public boolean hasId() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required string id = 1;</code>
             */
            public String getId() {
                Object ref = id_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    id_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string id = 1;</code>
             */
            public com.google.protobuf.ByteString
            getIdBytes() {
                Object ref = id_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string id = 1;</code>
             */
            public Builder setId(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string id = 1;</code>
             */
            public Builder clearId() {
                bitField0_ = (bitField0_ & ~0x00000001);
                id_ = getDefaultInstance().getId();
                onChanged();
                return this;
            }

            /**
             * <code>required string id = 1;</code>
             */
            public Builder setIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                id_ = value;
                onChanged();
                return this;
            }

            // required bool success = 2;
            private boolean success_;

            /**
             * <code>required bool success = 2;</code>
             */
            public boolean hasSuccess() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required bool success = 2;</code>
             */
            public boolean getSuccess() {
                return success_;
            }

            /**
             * <code>required bool success = 2;</code>
             */
            public Builder setSuccess(boolean value) {
                bitField0_ |= 0x00000002;
                success_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required bool success = 2;</code>
             */
            public Builder clearSuccess() {
                bitField0_ = (bitField0_ & ~0x00000002);
                success_ = false;
                onChanged();
                return this;
            }

            // required string msg = 3;
            private Object msg_ = "";

            /**
             * <code>required string msg = 3;</code>
             */
            public boolean hasMsg() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>required string msg = 3;</code>
             */
            public String getMsg() {
                Object ref = msg_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    msg_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>required string msg = 3;</code>
             */
            public com.google.protobuf.ByteString
            getMsgBytes() {
                Object ref = msg_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    msg_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string msg = 3;</code>
             */
            public Builder setMsg(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                msg_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>required string msg = 3;</code>
             */
            public Builder clearMsg() {
                bitField0_ = (bitField0_ & ~0x00000004);
                msg_ = getDefaultInstance().getMsg();
                onChanged();
                return this;
            }

            /**
             * <code>required string msg = 3;</code>
             */
            public Builder setMsgBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                msg_ = value;
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Responce)
        }

        static {
            defaultInstance = new Responce(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:Responce)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Request_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Request_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_Responce_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Responce_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\017TestModel.proto\"G\n\007Request\022\n\n\002id\030\001 \002(\t" +
                        "\022\020\n\010deviceId\030\002 \002(\t\022\016\n\006userId\030\003 \002(\t\022\016\n\006me" +
                        "thod\030\004 \002(\t\"4\n\010Responce\022\n\n\002id\030\001 \002(\t\022\017\n\007su" +
                        "ccess\030\002 \002(\010\022\013\n\003msg\030\003 \002(\tB\027\n\025com.xiyuan.d" +
                        "emo.model"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_Request_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_Request_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Request_descriptor,
                                new String[]{"Id", "DeviceId", "UserId", "Method",});
                        internal_static_Responce_descriptor =
                                getDescriptor().getMessageTypes().get(1);
                        internal_static_Responce_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_Responce_descriptor,
                                new String[]{"Id", "Success", "Msg",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
